### ISSUE TITLE
設定ファイルをYAMLにする

### ISSUE THREAD

**Issue by tsubasa-utsumi** [tsubasa-utsumi/MyNotifier#5]
INIファイルはダサいし使いづらいのでYAMLを使ってみる。
これにより、複数ユーザでの複数の監視対象を保持する事が楽になる。はず。

- [x] 現在の設定ファイルをYAMLに変更
- [x] 監視対象をYAMLで管理(運用側)

**Comment by tsubasa-utsumi** [comment]
データ構造案

構造
```
kindle:
- name: アカウント名
  url:
  - [URL, 割引率]
```

記述例
```
kindle:
- name: utsumin
  url:
  - ['https://www.amazon.com/a', 40]
  - ['https://www.amazon.com/b', 30]
- name: ahoahoman
  url:
  - ['https://www.amazon.com/a', 40]
  - ['https://www.amazon.com/b', 30]
  - ['https://www.amazon.com/c', 60]
  - ['https://www.amazon.com/d', 70]
  - ['https://www.amazon.com/e', 80]
```
